### ISSUE TITLE
Make PropagatorOpts fields public

### ISSUE THREAD

**Issue by aantono** [ExpediaDotCom/haystack-client-go#14]
With the inner fields being private, https://github.com/ExpediaDotCom/haystack-client-go/blob/master/propagator.go#L67-L70  it is impossible to construct a propagator from outside the package with alternative keys, as they can only be set inside the package (which defeats the point of having options to begin with)

**Comment by absrivastava** [comment]
Released with 0.2.2 (https://github.com/ExpediaDotCom/haystack-client-go/releases/tag/0.2.2)
