### ISSUE TITLE
add HTTPHeadersCarrier support

### ISSUE THREAD

**Issue by graphaelli** [ExpediaDotCom/haystack-client-go#17]
The [opentracing example code](https://github.com/opentracing/opentracing-go#serializing-to-the-wire) works with various go opentracers, but not with haystack:

```go
span := opentracing.StartSpan("root")
defer span.Finish()
req, _ := http.NewRequest(http.MethodGet, "https://expediadotcom.github.io/haystack/", nil)
err := tracer.Inject(span.Context(), opentracing.HTTPHeaders, opentracing.HTTPHeadersCarrier(req.Header))
if err != nil {
	fmt.Println(err)
}
# ... use req
fmt.Println(req.Header)
```
causing a panic:
```
panic: interface conversion: interface {} is opentracing.HTTPHeadersCarrier, not map[string]string
```

at https://github.com/ExpediaDotCom/haystack-client-go/blob/3ee3ba12ce07ae900855f7cf3e3f543418e865bf/propagator.go#L116

A committed user could make this work with something like:
```go
span := opentracing.StartSpan("root")
defer span.Finish()
req, _ := http.NewRequest(http.MethodGet, "https://expediadotcom.github.io/haystack/", nil)
headers := make(map[string]string)
err := tracer.Inject(span.Context(), opentracing.HTTPHeaders, headers)
if err != nil {
	fmt.Println(err)
} else {
	for k, v := range headers {
		req.Header.Add(k, v)
	}
}
# ... use req
fmt.Println(req.Header)
```

but that defeats the promise of opentracing.

The same issue exists on [Extract](https://github.com/ExpediaDotCom/haystack-client-go/blob/3ee3ba12ce07ae900855f7cf3e3f543418e865bf/propagator.go#L132).

**Comment by ashishagg** [comment]
Thanks for reporting this issue. PR has been raised to fix this.
Updated the example that is closer to opentracing usage

**Comment by ashishagg** [comment]
@graphaelli can you confirm if this works for you? I will release the library on coming Mon.

**Comment by graphaelli** [comment]
looks good, thank you
